name: Crear SVG XYVENQORIX

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Crear imagen SVG
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generar SVG
        uses: jasineri/gitartwork@v1
        with:
          user_name: xyvenqorix
          text: XYVENQORIX

      - name: Guardar SVG en el repositorio
        uses: jasineri/simple-push-action@v1
